### ISSUE TITLE
Page backup mode should error out when a database has been created

### ISSUE THREAD

**Issue by frost242** [michaelpq/pg_arman#24]
Hello,

The documentation already warns that one should take a full backup after the user has created a new database. It would be safer if pg_arman errors out when it detects that a database has been created.

Is it feasible without too much effort and overhead ?

Anyway, it's a very interesting tool ! Thanks for maintaining it.

Regards,
Thomas

**Comment by stalkerg** [comment]
>The documentation already warns that one should take a full backup after the user has created a new database. It would be safer if pg_arman errors out when it detects that a database has been created.

I'am not sure that's true now.

**Comment by michaelpq** [comment]
It may be worth a try, I was aware of this limitation beforehand.

**Comment by frost242** [comment]
I'll do some more tests when I find some time and let you know.

**Comment by michaelpq** [comment]
Some testing and code checks are proving me that this is working fine. You can create a database, then do a differential backup, and then when restoring using this differential backup the new database is here. That's an advantage of doing the differential backup thanks to the block scanning in WAL records. I have fixed the documentation with 05601aa.
