### ISSUE TITLE
Compilation error: util.c:19:2: error: unknown type name ‘pg_crc32c’

### ISSUE THREAD

**Issue by ARogovsky** [michaelpq/pg_arman#26]
`~/pg_arman# LC_ALL=C make USE_PGXS=1 top_srcdir=../postgresql-9.4-9.4.6/
No docs to build
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -I/usr/include/postgresql -I. -I./ -I/usr/include/postgresql/9.4/server -I/usr/include/postgresql/internal -DFRONTEND   -c -o util.o util.c
util.c: In function 'checkControlFile':
util.c:19:2: error: unknown type name 'pg_crc32c'
  pg_crc32c   crc;
  ^
util.c:22:2: warning: implicit declaration of function 'INIT_CRC32C' [-Wimplicit-function-declaration]
  INIT_CRC32C(crc);
  ^
util.c:23:2: warning: implicit declaration of function 'COMP_CRC32C' [-Wimplicit-function-declaration]
  COMP_CRC32C(crc, (char *) ControlFile, offsetof(ControlFileData, crc));
  ^
util.c:24:2: warning: implicit declaration of function 'FIN_CRC32C' [-Wimplicit-function-declaration]
  FIN_CRC32C(crc);
  ^
util.c:27:5: warning: implicit declaration of function 'EQ_CRC32C' [-Wimplicit-function-declaration]
     if (!EQ_CRC32C(crc, ControlFile->crc))
     ^
<builtin>: recipe for target 'util.o' failed
make: *** [util.o] Error 1
`

**Comment by stalkerg** [comment]
Sorry but current pg_arman support Postgres 9.5 and higher.

**Comment by michaelpq** [comment]
Yes, having support for <= 9.4 is not that complicated, but this requires a lot of mambo-jumbo for WAL record parsing that will not make the code more readable, far from that.
