### ISSUE TITLE
Stange error in delete test

### ISSUE THREAD

**Issue by stalkerg** [michaelpq/pg_arman#29]
Sometimes on debian-8-x86_64 we have additional line for delete test:
NOTICE:  pg_stop_backup cleanup done, waiting for required WAL segments to be archived

Diff:
```diff
================= pgsql.build/contrib/pg_arman/regression.diffs ===================
*** /app/data/PGPRO_pg_arman/pgsql.build/contrib/pg_arman/expected/delete.out	Fri Mar 25 11:37:50 2016
--- /app/data/PGPRO_pg_arman/pgsql.build/contrib/pg_arman/results/delete.out	Fri Mar 25 12:36:00 2016
***************
*** 10,15 ****
--- 10,16 ----
  Number of deleted backups should be 1, is it so?: 1
  ###### DELETE COMMAND TEST-0002 ######
  ###### keep backups which are necessary for recovery ######
+ NOTICE:  pg_stop_backup cleanup done, waiting for required WAL segments to be archived
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
  NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
```

This NOTICE have in 10493 line of xlog.c (postgres) but I do not know how to fix it properly.

Thanks.

**Comment by michaelpq** [comment]
I agree that this is noise, and that are those logs are actually useless noise. Those entries are generated within libpq when executing pg_stop_backup() and one way to get rid of them is to use "SET client_min_messages = warning" on the connection used, which is what I did in 8c66f1b7, sanitizing at the same time some of the regression outputs.
